= Abstract

== Problèmes constatés

* J'ai beaucoup bossé sur des projets qui démarrent "from scratch" où tous les choix techniques sont ouverts et possibles, sans contraintes (ou très peu). Du coup, quand on se retrouve face à une codebase front qui a plus de 7 ans, comment peut-on mettre à jour une partie de la stack sans faire de big bang où on réécrit tout.
* J'ai assisté à beaucoup de conférences frontend qui me parlent de nouvelles technos/outils/fwks mais rarement dans un contexte de migration en cours de route. Le plus souvent, le contexte est "voici un nouveau truc qui brille pour ton nouveau projet".
* J'ai assisté à beaucoup de conférences où on m'explique comment fonctionne une techno mais pas forcément comment telle personne l'utilise en prod dans la vraie vie.

== Conclusion

Ajouter des technos/outils modernes et adopter de nouvelles méthodes/approches dans les contraintes du legacy, c'est possible et c'est très enrichissant intellectuellement.

== Take away

Une personne qui a suivi la présentation repart avec :

* Des idées/approches de comment mettre à jour une partie de la stack d'une webapp legacy en prod.
* Une méthode pour développer des composants UI bas/haut niveau (penser I/O, docs, tous les états, découplage).
* Un outil et une approche pour découpler ses composants du contexte d'utilisation (storybook).
* Une conviction que les Web Components en prod ça marche et un aperçu des avantages inconvénients.

== Déroulé simplifié

Retour d'expérience de la mise à jour progressive de la console Clever Cloud (technique et fonctionnelle).

* Bonjour à tous
* Notre contexte
* Notre besoin
* Les solutions et méthodos mises en place : voyage à travers nos aventures
** Adoption des Web Components avec LitElement
*** Minification (pb avec les variables privées)
** ESlint (on devrait péter au commit)
** Intégration de ces composants dans du legacy jQuery et du Vue.js
*** pb des raccourcis clavier et du routeur (un jour du password manager)
** Mise en place de Storybook
*** Méthodo de Storybook Driven Development (story puis dev, penser à tous les cas)
*** Penser a11y, responsive et i18n
** Génération auto de la doc d'interface de nos composants avec WCA
** Démarche de choix de dépendance et polyfill et standard etc...
** Feature branches du Storybook
** Mise en OSS du Storybook
** Maj du système de i18n
*** i18n-extract, code analysis
** Mise en place de code-splitting et de lazy loading des routes (webpack)
** Mise à jour de notre client REST (pour le rendre dynamique)
** Mise en place d'ADR (ou de documents dans le genre)
** Tâche de size pr analyser l'impact
** ...
* La suite ?

== Abstract

=== FR

Après avoir principalement connu des projets frontend from-scratch, je me suis confronté à un challenge différent : travailler sur la console d'admin de Clever Cloud.
Une base de code "legacy" qui a plus de 10 ans, sans framework JS à la mode et qui n'a jamais connu de refonte big-bang.

Comment fait-on pour introduire les outils et méthodes d'aujourd'hui dans une app legacy en prod sur laquelle on assure un support quotidien (bugfixs et nouvelles fonctionnalités) ?

Depuis un an, nous avons développé une collection de Web Components avec LitElement que nous avons intégré dans différentes apps : jQuery, Vue.js, Play/Scala, ...
Ils ont été développé dans un projet à part avec une méthode de conception/dev autour de Storybook.
Nous essayons d'automatiser au mieux (i18n, feature branch preview, component API docs) et nous avons fait le choix de partager publiquement cet effort (code source, issues, docs, ADR).

Durant cette session, je vous propose un retour d'expérience sur ce voyage de modernisation progressive : contexte, besoin, technos/méthodes mises en place, le positif/négatif...

=== EN

After a lot of frontend jobs with projects started from-scratch, I encountered a different challenge: working on the admin console of Clever Cloud.
A 10 years old legacy codebase, without any trendy JS framework that never had any big-bang refactor.

How do you introduce new tools and methods in a legacy app running in production that you support on a daily basis (bugfixes and new features)?

A year ago, we started a collection of Web Components using LitElement which we integrated in different apps: jQuery, Vue.js, Play/Scala, ...
They've been developed in a separated project with a design/dev method around Storybook.
We try to automate what we can (i18n, feature branch preview, component API docs) and we chose to publicly share this effort (source code, issues, docs, ADR).

In this session, we'll see lessons learned from this progressive migration journey : context, requirements, tools/methods we introduced, pros/cons...

== Message pour le comité

=== FR

En décidant d'introduire des Web Components (avec LitElement) dans notre vieille web app legacy (jQuery), nous avons essuyé pas mal de plâtres.
On a tenté des idées, mis en place des nouveaux outils, technos et méthodes.

Dans cette session, j'ai envie de proposer un retour d'expérience et de partager ce qui a bien marché dans notre contexte pour inspirer des idées au public.
À l'image d'une carte de randonnée avec plusieurs étapes, je m'arrêterai sur le pourquoi/comment des points les plus importants et intéressants de cette mise à jour progressive de legacy.
Les points que j'aborderai en fonction de ce que le temps permet :

* Web Components avec LitElement
* Intégration de ces composants dans différent contextes (jQuery, Vue.js...)
* Développement dans un Storybook à part avec feature branch preview auto
* Génération auto de la doc de Web Component avec WCA
* Comment on choisi nos dépendances tierces (polyfill, standards...)
* Publication open source
* i18n avec code analysis
* Code-splitting + lazy loading par route (webpack)
* Docs et ADR

=== EN

When we decided to introduce Web Components (with LitElement) in our old legacy web app (jQuery), we went through a difficult journey.
We tried many ideas and introduced new tools and methods.

In this session, I want to propose a "lessons learned" kind of talk to share what worked and what didn't for our context to inspire some ideas to the audience.
Just like a hiking map with different steps, I'll stop by the most important and interesting points of this progressive update with the why and the how.
Here are the points I would address, depending on what the time allows:

* Web Components with LitElement
* Integrating those components in different contexts (jQuery, Vue.js...)
* Developing them in a separated Storybook with auto feature branch preview
* Web Component docs auto generated with WCA
* How do we choose our third party dependencies (polyfill, standards...)
* Published as open source
* i18n with code analysis
* Code-splitting + lazy loading by route (webpack)
* Docs and ADR

== Idées de titre

REX : Faire du neuf avec du vieux, technos et méthodos modernes dans une web app legacy

Lessons learned: Modern tools and methods in a legacy web app

=== Autres

REX : introduire des technos/méthodos d'aujourd'hui dans du code legacy d'hier
REX : technos/méthodos modernes + base de code legacy = ❤
REX : technos/méthodos modernes + base de code legacy = love
Faire du vieux avec du neuf : technos/méthodos modernes dans une base legacy
REX : Faire du neuf avec du vieux, technos/méthodos modernes dans une base legacy
REX : Faire du neuf avec du vieux, technos/méthodos Web modernes dans une base legacy
